const watches=[
 {id:1,from:'台北 TPE',to:'東京 NRT',dates:'11/12 — 11/17',people:'1 位成人 · 經濟艙',price:8420,target:9000,rule:'來回 · 直飛優先',when:'10 分鐘前',delta:-780},
 {id:2,from:'台北 TPE',to:'大阪 KIX',dates:'12/04 — 12/08',people:'2 位成人 · 經濟艙',price:17860,target:16000,rule:'來回 · 不限轉機',when:'2 小時前',delta:1860},
 {id:3,from:'高雄 KHH',to:'曼谷 BKK',dates:'01/15 — 01/20',people:'1 位成人 · 經濟艙',price:7650,target:8000,rule:'來回 · 直飛優先',when:'5 小時前',delta:-420}
];
const providers=[
 {name:'Skyscanner',tag:'比價結果 · 示意報價',out:'08:40',back:'15:10',time:'3 小時 20 分',stop:'直飛',price:8420,url:'https://www.skyscanner.com.tw/'},
 {name:'Google Flights',tag:'前往 Google 搜尋',out:'09:15',back:'16:05',time:'3 小時 25 分',stop:'直飛',price:8710,url:'https://www.google.com/travel/flights?hl=zh-HK'},
 {name:'Trip.com',tag:'前往 Trip.com 搜尋',out:'13:30',back:'19:25',time:'3 小時 40 分',stop:'直飛',price:8945,url:'https://tw.trip.com/'}
];
const $=id=>document.getElementById(id), money=n=>`NT$ ${n.toLocaleString('zh-TW')}`;
function card(w){const hit=w.price<=w.target;const label=hit?'已達標':'監看中';const delta=hit?`比上次便宜 ${money(Math.abs(w.delta))}`:`距目標 ${money(w.delta)}`;return `<article class="watch-card ${hit?'reached':''}"><span class="status ${hit?'reached':''}">${hit?'●':'○'} ${label}</span><h3>${w.from} <span>→</span> ${w.to}</h3><p class="meta">${w.dates} · ${w.people}</p><div class="fare"><span>目前最低觀測價<br><small>${w.rule}</small></span><strong>${money(w.price)}<small>／人</small></strong></div><footer class="card-foot"><span>${w.when}</span><span class="${hit?'down':'up'}">${delta}</span></footer></article>`}
function renderWatches(filter='all'){const visible=watches.filter(w=>filter==='all'||filter==='target'&&w.price<=w.target||filter==='watching'&&w.price>w.target);$('watchGrid').innerHTML=visible.map(card).join('')||'<p>目前沒有符合條件的監看。</p>';$('homeWatches').innerHTML=watches.slice(0,3).map(card).join('');$('allCount').textContent=watches.length;$('targetCount').textContent=watches.filter(w=>w.price<=w.target).length;$('watchCount').textContent=watches.filter(w=>w.price>w.target).length}
function renderStats(){const hit=watches.filter(w=>w.price<=w.target).length;$('stats').innerHTML=`<div class="stat"><span>正在監看的旅程</span><strong>${watches.length} <small>條</small></strong></div><div class="stat"><span>已達目標價格</span><strong>${hit} <small>條</small></strong></div><div class="stat"><span>這次捕捉的降幅</span><strong>NT$ 1,200 <small>起</small></strong></div>`}
function renderActivity(){$('activityList').innerHTML='<div class="activity-row"><span class="activity-mark">↓</span><div><b>台北 → 東京 降 NT$780</b><span>剛剛更新 · 已低於你的目標價</span></div></div><div class="activity-row"><span class="activity-mark">✦</span><div><b>高雄 → 曼谷 出現直飛選擇</b><span>5 小時前 · 已加入監看結果</span></div></div>'}
function renderOffers(){const origin=$('origin').value,destination=$('destination').value;$('routeTitle').textContent=`${origin.replace(/（.*?）/,'')} → ${destination.replace(/（.*?）/,'')}`;$('routeMeta').textContent=`${$('departure').value} — ${$('returnDate').value} · ${$('travellers').value}`;$('offers').innerHTML=providers.map(p=>`<article class="offer"><div class="provider">${p.name}<small>${p.tag}</small></div><div><div class="flight"><b>${p.out}</b><i class="line"></i><b>${p.back}</b><span>${p.stop}</span></div><p class="offer-meta">${p.time} · 行李規則請於平台確認 · 含稅價格以結帳頁為準</p></div><div class="offer-price"><strong>${money(p.price)}</strong><small>每位成人 · 來回示意</small><button class="book" data-url="${p.url}">查看平台報價 ↗</button></div></article>`).join('')}
function view(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));window.scrollTo({top:0,behavior:'smooth'})}function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3300)}function swap(a,b){[a.value,b.value]=[b.value,a.value]}
document.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',()=>view(x.dataset.view)));$('swapQuick').onclick=()=>swap($('quickOrigin'),$('quickDestination'));$('swapSearch').onclick=()=>swap($('origin'),$('destination'));$('quickSearch').onclick=()=>{ $('origin').value=$('quickOrigin').value;$('destination').value=$('quickDestination').value;$('departure').value=$('quickDeparture').value;$('returnDate').value=$('quickReturn').value;renderOffers();view('search')};$('searchForm').onsubmit=e=>{e.preventDefault();renderOffers();toast('已更新示意比價結果；實際價格請在平台確認。')};document.querySelectorAll('#newWatch,#newWatchHome').forEach(x=>x.onclick=()=>$('watchDialog').showModal());$('closeDialog').onclick=()=>$('watchDialog').close();$('watchForm').onsubmit=e=>{e.preventDefault();const target=Number($('watchTarget').value),price=Math.round(target*1.11/10)*10;watches.unshift({id:Date.now(),from:$('watchOrigin').value,to:$('watchDestination').value,dates:`${$('watchDeparture').value.slice(5).replace('-','/')} — ${$('watchReturn').value.slice(5).replace('-','/')}`,people:'1 位成人 · 經濟艙',price,target,rule:`來回 · ${$('watchDirect').value}`,when:'剛剛建立',delta:price-target});$('watchDialog').close();renderWatches();renderStats();toast(`已開始監看 ${$('watchOrigin').value} → ${$('watchDestination').value}`)};document.addEventListener('click',e=>{const url=e.target.closest('[data-url]');if(url)window.open(url.dataset.url,'_blank','noopener');const filter=e.target.closest('[data-filter]');if(filter){document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));filter.classList.add('active');renderWatches(filter.dataset.filter)}});$('notificationButton').onclick=()=>{$('notificationBadge').style.display='none';toast('台北 → 東京已低於你的目標價 NT$9,000。')};renderWatches();renderStats();renderActivity();renderOffers();
