'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>new Intl.NumberFormat('zh-TW',{style:'currency',currency:'TWD',maximumFractionDigits:0}).format(n);
const KEY='flight-radar-v2', airports={
  // 台灣與港澳
  'TPE':'台北桃園','TSA':'台北松山','KHH':'高雄小港','RMQ':'台中清泉崗','HUN':'花蓮','MZG':'澎湖馬公','KIN':'金門','LZN':'馬祖南竿','HKG':'香港','MFM':'澳門',
  // 日本、韓國與中國大陸
  'NRT':'東京成田','HND':'東京羽田','KIX':'大阪關西','ITM':'大阪伊丹','NGO':'名古屋中部','FUK':'福岡','CTS':'札幌新千歲','OKA':'沖繩那霸','HIJ':'廣島','SDJ':'仙台','ICN':'首爾仁川','GMP':'首爾金浦','PUS':'釜山金海','CJU':'濟州','PEK':'北京首都','PKX':'北京大興','PVG':'上海浦東','SHA':'上海虹橋','CAN':'廣州白雲','SZX':'深圳寶安','XMN':'廈門高崎','CTU':'成都天府','CKG':'重慶江北','WUH':'武漢天河','XIY':'西安咸陽','KMG':'昆明長水',
  // 東南亞、南亞與中東
  'BKK':'曼谷素萬那普','DMK':'曼谷廊曼','CNX':'清邁','HKT':'普吉','SIN':'新加坡樟宜','KUL':'吉隆坡','PEN':'檳城','BKI':'亞庇','DPS':'峇里島登巴薩','CGK':'雅加達','SGN':'胡志明市','HAN':'河內','DAD':'峴港','MNL':'馬尼拉','CEB':'宿霧','VTE':'永珍','PNH':'金邊','RGN':'仰光','DEL':'德里','BOM':'孟買','BLR':'班加羅爾','CMB':'可倫坡','KTM':'加德滿都','DXB':'杜拜','AUH':'阿布達比','DOH':'杜哈','IST':'伊斯坦堡','TLV':'特拉維夫',
  // 大洋洲、歐洲與美洲
  'SYD':'雪梨','MEL':'墨爾本','BNE':'布里斯本','PER':'伯斯','AKL':'奧克蘭','CHC':'基督城','LHR':'倫敦希斯洛','LGW':'倫敦蓋特威克','CDG':'巴黎戴高樂','AMS':'阿姆斯特丹','FRA':'法蘭克福','MUC':'慕尼黑','ZRH':'蘇黎世','VIE':'維也納','FCO':'羅馬費米齊諾','MXP':'米蘭馬爾彭薩','BCN':'巴塞隆納','MAD':'馬德里','LIS':'里斯本','CPH':'哥本哈根','ARN':'斯德哥爾摩','OSL':'奧斯陸','HEL':'赫爾辛基','PRG':'布拉格','BUD':'布達佩斯','ATH':'雅典','KEF':'冰島凱夫拉維克','JFK':'紐約甘迺迪','EWR':'紐約紐華克','LAX':'洛杉磯','SFO':'舊金山','SEA':'西雅圖','ORD':'芝加哥歐海爾','DFW':'達拉斯沃斯堡','MIA':'邁阿密','YVR':'溫哥華','YYZ':'多倫多皮爾遜','MEX':'墨西哥城','GRU':'聖保羅','SCL':'聖地牙哥'
};
let state={version:2,watches:[],events:[],demo:false},page='home',filter='all',editing=null,selected=null,query=null,tripPage=0;
function pageSize(){return typeof window==='undefined'?3:window.innerWidth<750?1:window.innerWidth<1250?2:3;}
function pageTrips(ws){const size=pageSize();tripPage=Math.max(0,Math.min(tripPage,Math.ceil(ws.length/size)-1));return ws.slice(tripPage*size,(tripPage+1)*size);}
function pager(count){const total=Math.max(1,Math.ceil(count/pageSize()));return `<div class="pager"><span>${count} 筆旅程 · 第 ${tripPage+1} / ${total} 頁</span><button data-trip-page="-1" ${tripPage===0?'disabled':''}>上一頁</button><button data-trip-page="1" ${tripPage+1>=total?'disabled':''}>下一頁</button></div>`;}
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved&&saved.version===2&&Array.isArray(saved.watches)&&Array.isArray(saved.events))state=saved}catch{setTimeout(()=>toast('無法讀取舊資料，請從備份匯入。'),0)}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('儲存失敗：請匯出備份，檢查瀏覽器儲存權限。')}}
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4000)}
const route=w=>`${airports[w.from]||w.from} → ${airports[w.to]||w.to}`,price=w=>w.history?.length?w.history.at(-1).price:null,hit=w=>price(w)!==null&&price(w)<=w.target;

function tripText(w){return `${route(w)} (${w.from} → ${w.to})\n${w.trip==='round'?'來回':'單程'} · 去程 ${w.depart}${w.trip==='round'?' · 回程 '+w.return:''}\n${w.people} 位成人 · ${w.cabin} · ${w.direct?'只看直飛':'不限轉機'}\n預算總價 ${money(w.target)} · 幣別 TWD`;}
function lookupPanel(w,key){
return `<section class="lookup"><h3>外連查價</h3><p class="muted">先複製條件，再到平台輸入查價。各平台在新分頁開啟，票價以平台顯示為準。</p><textarea readonly aria-label="旅程查價條件" rows="4">${esc(tripText(w))}</textarea><button type="button" data-copy="${esc(key)}">複製全部條件</button><div class="platform-links">${[['Google Flights','https://www.google.com/travel/flights?hl=zh-TW'],['Skyscanner','https://www.skyscanner.com.tw/'],['Trip.com','https://tw.trip.com/']].map(([name,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${name} ↗<small>開啟平台・手動輸入條件</small></a>`).join('')}</div><p class="muted">查價時請確認往返日期、機場、人數、艙等、行李及含稅總價；App 不會自動讀取平台票價。</p></section>`;
}
async function copyTrip(key){const w=key==='query'?query:state.watches.find(x=>x.id===key);if(!w)return;try{await navigator.clipboard.writeText(tripText(w));toast('已複製旅程條件')}catch{toast('無法使用剪貼簿，請選取條件文字手動複製。')}}

function chart(w){if(!w.history?.length)return '<div class="empty">尚無價格觀測紀錄</div>';const vals=w.history.map(h=>h.price),max=Math.max(...vals,w.target)*1.1,min=Math.min(...vals,w.target)*.9,y=n=>110-(n-min)/(max-min||1)*85;return `<svg viewBox="0 0 400 135" role="img" aria-label="示意價格走勢與目標價"><line x1="10" x2="390" y1="${y(w.target)}" y2="${y(w.target)}" stroke="#eea338" stroke-dasharray="5 5"/><polyline points="${vals.map((n,i)=>`${15+i*365/Math.max(vals.length-1,1)},${y(n)}`).join(' ')}" fill="none" stroke="#009599" stroke-width="3"/><text x="15" y="130" fill="#607787" font-size="12">${esc(w.history[0].date)} — ${esc(w.history.at(-1).date)} · 示意</text></svg>`}
const photos={NRT:'photo-1591194233688-dca69d406068',HND:'photo-1591194233688-dca69d406068',KIX:'photo-1753165045682-707d0f1fa848',BKK:'photo-1753871486173-96ed6bb1b13f'};
function card(w){let p=price(w);return `<article class="card"><div class="cover">${photos[w.to]?`<img loading="lazy" src="https://images.unsplash.com/${photos[w.to]}?auto=format&fit=crop&w=900&q=80" alt="${esc(airports[w.to])}目的地照片">`: `<h2 style="padding:45px 20px;color:white">${esc(w.to)}</h2>`}<span class="pill">${w.paused?'已暫停':w.demo?'示意旅程':'自行查價'}</span></div><div class="card-body"><p class="muted">${esc(w.from)} → ${esc(w.to)} · ${w.trip==='oneway'?'單程':'來回'}</p><h3>${esc(route(w))}</h3><p class="muted">${esc(w.depart)}${w.trip==='round'?' — '+esc(w.return):''}<br>${w.people} 位成人 · ${esc(w.cabin)} · ${w.direct?'直飛限定':'不限轉機'}</p><div class="price">${p===null?'尚無報價':money(p)}</div><span class="muted">${p===null?'開啟旅程詳情，到平台查價':`全體旅客含稅示意總價 · 每人 ${money(p/w.people)}`}</span><div class="row"><span>目標 ${money(w.target)}</span><span class="pill">${p===null?'未取得報價':hit(w)?'示意已達標':`距目標 ${money(p-w.target)}`}</span></div><div class="card-bottom actions"><button data-detail="${w.id}">外連查價／詳情</button><button data-edit="${w.id}">編輯</button><button data-pause="${w.id}">${w.paused?'恢復':'暫停'}</button><button data-delete="${w.id}">刪除</button></div></div></article>`}
function events(limit=100){return state.events.slice(0,limit).map(e=>`<div class="event"><div><strong>${esc(e.type)}</strong><div>${esc(e.text)}</div><small>${esc(new Date(e.at).toLocaleString('zh-TW'))}${e.read?' · 已讀':''}</small></div><button data-event="${e.id}">查看</button></div>`).join('')||'<p class="empty">沒有新通知。啟用範例可預覽達標與降價通知。</p>'}
function render(){if(typeof document.body!=='undefined')document.body.dataset.view=page;document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('title').textContent=({home:'想去的地方，都在這裡。',watches:'每一段期待，值得留意。',search:'為下一次出發找好價格。',notifications:'旅程的最新消息。',settings:'你的旅行偏好與資料。'})[page];let out='';if(page==='home'||page==='watches'){let ws=state.watches.filter(w=>filter==='all'||filter==='paused'&&w.paused||filter==='active'&&!w.paused||filter==='hit'&&hit(w)&&!w.paused);out=`<div class="stats"><div class="stat"><span>監看旅程</span><strong>${state.watches.length}</strong></div><div class="stat"><span>已達標（示意）</span><strong>${state.watches.filter(hit).length}</strong></div><div class="stat"><span>查價方式</span><strong>外連平台</strong></div></div><div class="filters">${[['all','全部'],['active','啟用中'],['hit','已達標'],['paused','已暫停']].map(([v,l])=>`<button data-filter="${v}" class="${filter===v?'active':''}">${l}</button>`).join('')}</div><div class="grid">${pageTrips(ws).map(card).join('')}</div>${pager(ws.length)}${!ws.length?'<div class="panel empty"><h2>把下一個目的地加入雷達</h2><p>建立旅程、設定預算，條件會保存在這個瀏覽器。</p><button id="emptyAdd" class="primary">新增第一段旅程</button> <button id="demo">載入示意旅程</button></div>':''}`;if(page==='home')out+=`<div class="overview-footer"><span>查價前請確認行李、轉機與含稅總價。</span><button data-page="notifications">通知中心（${state.events.filter(e=>!e.read).length} 則未讀）</button></div>`}if(page==='search')out=`<form id="searchForm" class="panel search-panel"><div class="fields">${fields(query)}</div><button class="primary">套用搜尋條件</button></form><div id="results">${results()}</div>`;if(page==='notifications')out=`<div class="panel"><div class="row"><h2>通知中心</h2><button id="readAll">全部標為已讀</button></div>${events()}</div>`;if(page==='settings')out='<div class="panel"><h2>資料與範例</h2><p>資料只保存在目前瀏覽器，不會跨裝置同步；清除瀏覽器資料會移除監看。</p><div class="actions"><button id="export">匯出 JSON 備份</button><label>匯入備份<input id="import" type="file" accept="application/json,.json"></label><button id="demo">載入示意旅程</button></div><h2>服務連線</h2><p>即時報價：未接入<br>背景排程：未接入<br>Email / Push：未啟用</p><p class="muted">目前不會在關閉網頁後查價或傳送外部通知。</p></div>';$('content').innerHTML=out;if(page==='search'){wireForm($('searchForm'),false);demoOffers();}if($('import'))$('import').onchange=importFile}
function fields(w={}){w=w||{};const opts=(list,val)=>list.map(([v,l])=>`<option value="${esc(v)}" ${v===val?'selected':''}>${esc(l)}</option>`).join('');return `<label>出發機場<select name="from">${opts(Object.entries(airports).map(([k,v])=>[k,`${v} (${k})`]),w.from||'TPE')}</select></label><label>目的地機場<select name="to">${opts(Object.entries(airports).map(([k,v])=>[k,`${v} (${k})`]),w.to||'NRT')}</select></label><label>航程<select name="trip">${opts([['round','來回'],['oneway','單程']],w.trip||'round')}</select></label><label>旅客人數（成人）<input name="people" type="number" min="1" max="9" required value="${w.people||1}"></label><label>去程<input name="depart" type="date" required value="${esc(w.depart||'')}"></label><label>回程<input name="return" type="date" value="${esc(w.return||'')}"></label><label>艙等<select name="cabin">${opts(['經濟艙','豪華經濟艙','商務艙'].map(x=>[x,x]),w.cabin||'經濟艙')}</select></label><label>目標總價（所有旅客 TWD）<input name="target" type="number" min="1" max="10000000" required value="${w.target||10000}"></label><label><input name="direct" type="checkbox" ${w.direct?'checked':''}> 只看直飛</label><label><input name="alert" type="checkbox" ${w.alert!==false?'checked':''}> 啟用站內通知條件</label><p class="wide muted">通知條件會保存；真實自動通知尚未接入。</p>`}
function readForm(f){const d=new FormData(f),w=Object.fromEntries(d);w.people=Number(w.people);w.target=Number(w.target);w.direct=d.has('direct');w.alert=d.has('alert');if(w.from===w.to)throw Error('出發地與目的地不能相同。');const today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);if(!w.depart||w.depart<today)throw Error('去程日期不可早於今天。');if(w.trip==='round'&&(!w.return||w.return<w.depart))throw Error('回程不可早於去程。');if(w.trip==='oneway')w.return='';return w}
function wireForm(f,isEdit){const sync=()=>{f.elements.return.disabled=f.elements.trip.value==='oneway';f.elements.return.required=!f.elements.return.disabled};f.elements.trip.onchange=sync;sync();f.onsubmit=e=>{e.preventDefault();try{const w=readForm(f);if(!isEdit){query=w;render();demoOffers();return}const old=state.watches.find(x=>x.id===editing);const changed=old&&['from','to','trip','depart','return','people','cabin','direct'].some(k=>old[k]!==w[k]);const item={...old,...w,id:editing||crypto.randomUUID(),history:changed?[]:old?.history||[],demo:changed?false:old?.demo||false};if(old)state.watches[state.watches.indexOf(old)]=item;else state.watches.unshift(item);save();$('editor').close();render();toast('旅程已保存於此瀏覽器')}catch(err){if(isEdit)$('error').textContent=err.message;else toast(err.message)}}}
function edit(id){editing=id||null;const w=state.watches.find(x=>x.id===id);$('formTitle').textContent=w?'編輯監看':'新增監看';$('fields').innerHTML=fields(w);$('error').textContent='';wireForm($('form'),true);$('editor').showModal()}
function results(){if(!query)return '<div class="panel empty">設定旅程後，即可複製條件並開啟平台查價。</div>';return `<div class="panel"><h2>${esc(route(query))}</h2>${lookupPanel(query,'query')}<button id="saveQuery" class="primary">將這段旅程加入我的監看</button></div>`;}
function demoOffers(){if(!query||!$('demoOffers'))return;const list=[{name:'範例航班 A',p:8420,min:195,direct:true,bag:false},{name:'範例航班 B',p:9200,min:210,direct:true,bag:true},{name:'範例航班 C',p:7600,min:410,direct:false,bag:true}].filter(o=>(!query.direct||o.direct)&&(!$('baggage')?.checked||o.bag)).sort((a,b)=>$('sort')?.value==='duration'?a.min-b.min:a.p-b.p);if(!$('demoOffers'))return;$('demoOffers').innerHTML=list.map(o=>`<article class="offer"><span class="pill">介面範例 · 非實際航班</span><div class="row"><h3>${o.name}</h3><strong>${money(o.p*query.people)}／全體旅客</strong></div><div class="timeline"><b>${esc(query.from)}</b><hr><span>${o.min} 分鐘 · ${o.direct?'直飛':'轉機一次'}</span><hr><b>${esc(query.to)}</b></div><p class="muted">每人 ${money(o.p)} · ${o.bag?'含 20kg 托運（示意）':'行李未確認'}</p><details><summary>票種與平台比較</summary><table><tr><th>來源</th><th>含稅總價</th><th>退改條件</th></tr><tr><td>範例賣家 A</td><td>${money(o.p*query.people)}</td><td>未確認</td></tr><tr><td>範例賣家 B</td><td>${money((o.p+300)*query.people)}</td><td>未確認</td></tr></table></details></article>`).join('')||'<p class="empty">沒有符合篩選的範例航班。</p>'}
function detail(id){const w=state.watches.find(x=>x.id===id);if(!w){toast('這筆監看已不存在');return}selected=id;$('detailBody').innerHTML=`<h2>${esc(route(w))}</h2><p>${esc(w.depart)} · ${w.people} 位成人 · 目標總價 ${money(w.target)}</p>${lookupPanel(w,w.id)}${chart(w)}<p class="muted">橘色虛線：目標價。${w.demo?'所有觀測數字均為範例。':'尚未連接供應商，沒有真實觀測資料。'}</p><h3>觀測紀錄</h3>${w.history.length?`<table><tr><th>日期</th><th>全體旅客總價</th><th>類型</th></tr>${w.history.map(h=>`<tr><td>${esc(h.date)}</td><td>${money(h.price)}</td><td>示意</td></tr>`).join('')}</table>`:'<p>等待資料</p>'}<h3>這段旅程的通知</h3>${state.events.filter(e=>e.watch===id).map(e=>`<p>${esc(e.text)}</p>`).join('')||'<p>尚無通知</p>'}`;$('detail').showModal()}
function loadDemo(){if(state.watches.some(w=>w.demo)){toast('範例已載入');return}state.demo=true;const date=new Date();date.setDate(date.getDate()+60);const dep=date.toISOString().slice(0,10);date.setDate(date.getDate()+5);for(const [to,people,target,vals] of [['NRT',1,9000,[10300,9700,9300,8800,8420]],['KIX',2,16000,[19600,18900,18400,18100,17860]],['BKK',1,8000,[9100,8900,8400,8000,7650]]]){const id=crypto.randomUUID();state.watches.push({id,from:'TPE',to,depart:dep,return:date.toISOString().slice(0,10),trip:'round',people,target,cabin:'經濟艙',direct:true,alert:true,demo:true,history:vals.map((price,i)=>({date:`範例第 ${i+1} 次`,price}))});state.events.unshift({id:crypto.randomUUID(),watch:id,type:vals.at(-1)<=target?'示意達標':'示意降價',text:route({from:'TPE',to})+' 範例價格已更新',at:new Date().toISOString(),read:false})}save();render();toast('已載入三筆示意旅程')}
function validateImport(s){if(s?.version!==2||!Array.isArray(s.watches)||s.watches.length>1000||!Array.isArray(s.events)||s.events.length>5000)throw Error('備份格式不正確');const ids=new Set();for(const w of s.watches){if(typeof w.id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(w.id)||ids.has(w.id)||!airports[w.from]||!airports[w.to]||w.from===w.to||!['round','oneway'].includes(w.trip)||!Number.isInteger(w.people)||w.people<1||w.people>9||!Number.isFinite(w.target)||w.target<=0||!Array.isArray(w.history)||w.history.some(h=>!Number.isFinite(h.price)||h.price<=0)||!/^\d{4}-\d{2}-\d{2}$/.test(w.depart))throw Error('備份含有無效旅程');ids.add(w.id)}for(const e of s.events)if(typeof e.id!=='string'||typeof e.text!=='string'||typeof e.type!=='string'||!Number.isFinite(Date.parse(e.at)))throw Error('通知備份無效');return s}
async function importFile(e){try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('備份超過 2MB');const data=validateImport(JSON.parse(await file.text()));if(!confirm(`匯入 ${data.watches.length} 筆監看並取代目前本機資料？請先匯出備份。`))return;state=data;save();render();toast('匯入完成')}catch(err){toast(err.message)}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.copy)copyTrip(d.copy);if(b.id==='saveQuery'&&query){const exists=state.watches.some(w=>['from','to','trip','depart','return','people','cabin','direct'].every(k=>w[k]===query[k]));if(exists){toast('相同條件的旅程已經存在')}else{state.watches.unshift({...query,id:crypto.randomUUID(),history:[],demo:false});save();page='watches';filter='all';render();toast('已加入我的監看')}}if(d.tripPage){tripPage+=Number(d.tripPage);render()}if(d.page){page=d.page;tripPage=0;render()}if(d.filter){filter=d.filter;tripPage=0;render()}if(d.edit)edit(d.edit);if(d.detail)detail(d.detail);if(d.pause){const w=state.watches.find(x=>x.id===d.pause);w.paused=!w.paused;save();render()}if(d.delete&&confirm('刪除這筆監看？可先在設定匯出備份。')){state.watches=state.watches.filter(w=>w.id!==d.delete);save();render()}if(d.event){const event=state.events.find(x=>x.id===d.event);event.read=true;save();render();detail(event.watch)}if(['add','emptyAdd'].includes(b.id))edit();if(b.id==='demo')loadDemo();if(b.id==='cancel')$('editor').close();if(b.id==='closeDetail')$('detail').close();if(b.id==='readAll'){state.events.forEach(x=>x.read=true);save();render()}if(b.id==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='flight-radar-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}if(page==='search')demoOffers()});document.addEventListener('change',e=>{if(['sort','baggage'].includes(e.target.id))demoOffers()});render();


if(typeof window!=='undefined'){let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(page==='home'||page==='watches')render()},180)});}
