'use strict';
/* Manual price log plus parameterized lookup links. */
const actuals=w=>Array.isArray(w.checks)?w.checks:[];
const currentPrice=w=>actuals(w).length?actuals(w).at(-1).price:(w.history?.length?w.history.at(-1).price:null);
const cabinCode=c=>({'經濟艙':'economy','豪華經濟艙':'premiumeconomy','商務艙':'business','頭等艙':'first'}[c]||'economy');
function googleFlightUrl(w){return 'https://www.google.com/travel/flights?hl=zh-TW&curr=TWD&q='+encodeURIComponent(`Flights from ${w.from} to ${w.to} departing ${w.depart}${w.trip==='round'?` returning ${w.return}`:''} ${w.people} adult ${w.cabin}`)}
function skyscannerUrl(w){const q=new URLSearchParams({market:'TW',locale:'zh-TW',currency:'TWD',origin:w.from,destination:w.to,outboundDate:w.depart,adultsv2:String(w.people),cabinclass:cabinCode(w.cabin),preferDirects:String(Boolean(w.direct))});if(w.trip==='round')q.set('inboundDate',w.return);return 'https://www.skyscanner.net/g/referrals/v1/flights/day-view/?'+q}
function chart(w){const entries=actuals(w).length?actuals(w).map(x=>({price:x.price,date:new Date(x.at).toLocaleDateString('zh-TW')})):(w.history||[]);if(!entries.length)return '<div class="empty">尚無價格紀錄</div>';const vals=entries.map(x=>x.price),max=Math.max(...vals,w.target)*1.1,min=Math.min(...vals,w.target)*.9,y=n=>110-(n-min)/(max-min||1)*85;return `<svg viewBox="0 0 400 135" role="img" aria-label="價格走勢與目標價"><line x1="10" x2="390" y1="${y(w.target)}" y2="${y(w.target)}" stroke="#eea338" stroke-dasharray="5 5"/><polyline points="${vals.map((n,i)=>`${15+i*365/Math.max(vals.length-1,1)},${y(n)}`).join(' ')}" fill="none" stroke="#009599" stroke-width="3"/><text x="15" y="130" fill="#607787" font-size="12">${esc(entries[0].date)} — ${esc(entries.at(-1).date)} · ${actuals(w).length?'手動查價':'示意'}</text></svg>`}
function lookupPanel(w,key){return `<section class="lookup"><h3>查價工作台</h3><p class="muted">Google Flights 與 Skyscanner 會帶入條件；Trip.com 使用複製條件。</p><textarea readonly aria-label="旅程查價條件" rows="4">${esc(tripText(w))}</textarea><button type="button" data-copy="${esc(key)}">複製全部條件</button><div class="platform-links"><a href="${googleFlightUrl(w)}" target="_blank" rel="noopener noreferrer">Google Flights ↗<small>帶入文字條件</small></a><a href="${skyscannerUrl(w)}" target="_blank" rel="noopener noreferrer">Skyscanner ↗<small>帶入航線與篩選</small></a><a href="https://tw.trip.com/" target="_blank" rel="noopener noreferrer">Trip.com ↗<small>複製條件後貼上</small></a></div></section>`}
function card(w){const p=currentPrice(w),label=actuals(w).length?'手動查價總價':w.history?.length?'示意總價':'尚未記錄價格';return `<article class="card"><div class="cover">${photos[w.to]?`<img loading="lazy" src="https://images.unsplash.com/${photos[w.to]}?auto=format&fit=crop&w=900&q=80" alt="${esc(airports[w.to])}目的地照片">`:`<h2 style="padding:45px 20px;color:white">${esc(w.to)}</h2>`}<span class="pill">${w.paused?'已暫停':actuals(w).length?'已記錄價格':'自行查價'}</span></div><div class="card-body"><p class="muted">${esc(w.from)} → ${esc(w.to)} · ${w.trip==='oneway'?'單程':'來回'}</p><h3>${esc(route(w))}</h3><p class="muted">${esc(w.depart)}${w.trip==='round'?' — '+esc(w.return):''}<br>${w.people} 位成人 · ${esc(w.cabin)} · ${w.direct?'直飛限定':'不限轉機'}</p><div class="price">${p===null?'尚無報價':money(p)}</div><span class="muted">${p===null?'開啟詳情，到平台查價後保存價格':`${label} · 每人 ${money(p/w.people)}`}</span><div class="row"><span>目標 ${money(w.target)}</span><span class="pill">${p===null?'未取得報價':p<=w.target?'已達目標':`距目標 ${money(p-w.target)}`}</span></div><div class="card-bottom actions"><button data-detail="${w.id}">查價／保存結果</button><button data-edit="${w.id}">編輯</button><button data-pause="${w.id}">${w.paused?'恢復':'暫停'}</button><button data-delete="${w.id}">刪除</button></div></div></article>`}
function checkForm(w){return `<form class="check-form" data-check-form="${esc(w.id)}"><h3>保存這次查價</h3><div class="check-fields"><label>平台<select name="provider"><option>Google Flights</option><option>Skyscanner</option><option>Trip.com</option><option>航空公司官網</option><option>其他</option></select></label><label>全體旅客含稅總價（TWD）<input name="price" type="number" min="1" required placeholder="例如 16800"></label><label><input name="baggage" type="checkbox"> 已確認含托運行李</label><label>結果／訂購網址（選填）<input name="url" type="url" placeholder="https://..."></label></div><button class="primary">保存本次價格</button></form>`}
function checkRows(w){return actuals(w).length?`<table><tr><th>時間</th><th>平台</th><th>總價</th><th>行李</th></tr>${actuals(w).slice().reverse().map(c=>`<tr><td>${esc(new Date(c.at).toLocaleString('zh-TW'))}</td><td>${c.url?`<a href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">${esc(c.provider)}</a>`:esc(c.provider)}</td><td>${money(c.price)}</td><td>${c.baggage?'已確認':'未確認'}</td></tr>`).join('')}</table>`:'<p class="muted">尚未保存真實查價。完成平台查價後，在上方輸入總價。</p>'}
function detail(id){const w=state.watches.find(x=>x.id===id);if(!w){toast('這筆監看已不存在');return}$('detailBody').innerHTML=`<h2>${esc(route(w))}</h2><p>${esc(w.depart)} · ${w.people} 位成人 · 目標總價 ${money(w.target)}</p>${lookupPanel(w,w.id)}${checkForm(w)}${chart(w)}<p class="muted">橘色虛線是目標價。手動保存的價格會顯示在圖表中。</p><h3>查價紀錄</h3>${checkRows(w)}`;$('detail').showModal()}
document.addEventListener('submit',e=>{const f=e.target;if(!f.matches('[data-check-form]'))return;e.preventDefault();const w=state.watches.find(x=>x.id===f.dataset.checkForm),d=new FormData(f),value=Number(d.get('price')),url=String(d.get('url')||'').trim();if(!Number.isFinite(value)||value<=0){toast('請輸入正確的總價');return}if(url&&!/^https:\/\//i.test(url)){toast('網址必須以 https:// 開頭');return}const entry={id:crypto.randomUUID(),provider:String(d.get('provider')),price:value,baggage:d.has('baggage'),url,at:new Date().toISOString()};w.checks=[...actuals(w),entry];w.history=[...(w.history||[]),{date:new Date().toLocaleDateString('zh-TW'),price:value}];state.events.unshift({id:crypto.randomUUID(),watch:w.id,type:value<=w.target?'已達目標':'已保存查價',text:`${route(w)} · ${entry.provider} ${money(value)}`,at:entry.at,read:false});save();render();detail(w.id);toast('已保存本次查價')});
render();

